version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - sloglint
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - zerologlint
  settings:
    depguard:
      rules:
        logger:
          deny:
            - pkg: github.com/sirupsen/logrus
              desc: logging is allowed only by logutils.Log
    dupl:
      threshold: 100
    funlen:
      lines: -1
      statements: 80
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 45
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 215
    misspell:
      locale: US
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
      ignored-functions:
        - strings.SplitN
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: true
    revive:
      rules:
        - name: unexported-return
          disabled: true
        - name: unused-parameter
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: ".*operator-sdk:csv:customresourcedefinitions"
      - linters:
          - goconst
          - gocritic
          - ineffassign
          - mnd
          - revive
          - staticcheck
        path: _test\.go
      - path: pkg/golinters/errcheck.go
        text: 'SA1019: errCfg.Exclude is deprecated: use ExcludeFunctions instead'
      - path: pkg/commands/run.go
        text: 'SA1019: lsc.Errcheck.Exclude is deprecated: use ExcludeFunctions instead'
      - path: pkg/commands/run.go
        text: 'SA1019: e.cfg.Run.Deadline is deprecated: Deadline exists for historical compatibility and should not be used.'
      - path: pkg/golinters/gofumpt.go
        text: 'SA1019: settings.LangVersion is deprecated: use the global `run.go` instead.'
      - path: pkg/golinters/staticcheck_common.go
        text: 'SA1019: settings.GoVersion is deprecated: use the global `run.go` instead.'
      - path: pkg/lint/lintersdb/manager.go
        text: 'SA1019: (.+).(GoVersion|LangVersion) is deprecated: use the global `run.go` instead.'
      - path: pkg/golinters/unused.go
        text: 'rangeValCopy: each iteration copies 160 bytes \(consider pointers or indexing\)'
      - path: test/(fix|linters)_test.go
        text: string `gocritic.go` has 3 occurrences, make it a constant
    paths:
      - test/testdata_etc
      - internal/cache
      - internal/renameio
      - internal/robustio
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: interface{}
          replacement: any
    goimports:
      local-prefixes:
        - github.com/golangci/golangci-lint
  exclusions:
    generated: lax
    paths:
      - test/testdata_etc
      - internal/cache
      - internal/renameio
      - internal/robustio
      - third_party$
      - builtin$
      - examples$
