apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: patterns-operator-pattern-ui-catalog
  name: patterns-operator-pattern-ui-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: patterns-operator-pattern-ui-catalog
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app.kubernetes.io/component: patterns-operator-pattern-ui-catalog
    spec:
      containers:
      - image: quay.io/validatedpatterns/pattern-ui-catalog:stable-v1
        name: patterns-operator-pattern-ui-catalog
        ports:
        - containerPort: 9444
          name: https
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /var/cert
          name: pattern-ui-catalog-cert
          readOnly: true
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          readOnly: true
          subPath: nginx.conf
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      securityContext:
        runAsNonRoot: true
      serviceAccountName: patterns-operator-controller-manager
      volumes:
      - name: pattern-ui-catalog-cert
        secret:
          defaultMode: 420
          secretName: patterns-operator-pattern-ui-catalog-cert
      - name: nginx-conf
        configMap:
          defaultMode: 420
          name: patterns-operator-pattern-ui-catalog
