// Code generated by MockGen. DO NOT EDIT.
// Source: controllers/checkout.go
//
// Generated by this command:
//
//	mockgen -source controllers/checkout.go -package controllers -self_package=github.com/hybrid-cloud-patterns/patterns-operator/controllers
//
// Package controllers is a generated GoMock package.
package controllers

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGitOperations is a mock of GitOperations interface.
type MockGitOperations struct {
	ctrl     *gomock.Controller
	recorder *MockGitOperationsMockRecorder
}

// MockGitOperationsMockRecorder is the mock recorder for MockGitOperations.
type MockGitOperationsMockRecorder struct {
	mock *MockGitOperations
}

// NewMockGitOperations creates a new mock instance.
func NewMockGitOperations(ctrl *gomock.Controller) *MockGitOperations {
	mock := &MockGitOperations{ctrl: ctrl}
	mock.recorder = &MockGitOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitOperations) EXPECT() *MockGitOperationsMockRecorder {
	return m.recorder
}

// CloneAndCheckout mocks base method.
func (m *MockGitOperations) CloneAndCheckout(repoURL, revision, localFolder string, gitAuth map[string][]byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneAndCheckout", repoURL, revision, localFolder, gitAuth)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloneAndCheckout indicates an expected call of CloneAndCheckout.
func (mr *MockGitOperationsMockRecorder) CloneAndCheckout(repoURL, revision, localFolder, gitAuth any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneAndCheckout", reflect.TypeOf((*MockGitOperations)(nil).CloneAndCheckout), repoURL, revision, localFolder, gitAuth)
}
