name: Console

on:
  push:
    paths:
      - "console/**"
  pull_request:
    paths:
      - "console/**"

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Build the console container
      run: |
        make console-build-amd64
